### ISSUE TITLE
Clarify the validity of the produced Word document

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/metanorma-docker#2]
It needs to be made clear that the Word document produced is a valid MHT Word document which is fully supported by Windows.

Perhaps in the README somewhere.

**Comment by ronaldtse** [comment]
Thanks @ribose-jeffreylau! 

@opoudjis thoughts on where it should go?

**Comment by ribose-jeffreylau** [comment]
It's been reported that both Apple's version of "Word" (aka Pages) and LibreOffice would view the produced `.doc` file as "invalid".  This may also need clarification.

**Comment by opoudjis** [comment]
Documentation done in https://github.com/riboseinc/metanorma-iso/issues/220, as https://github.com/riboseinc/metanorma-iso/blob/master/docs/outputs.adoc . @ronaldtse, I leave the decision to you about how to incorporate this documentation into metanorma-docker, if at all.

**Comment by ronaldtse** [comment]
Is this a StanDoc issue, an ISO issue or a generic Metanorma issue? We should move the documentation to the right place(s). It’s definitely not a docker issue, so we are closing this here.

**Comment by opoudjis** [comment]
Generic Metanorma.
