### ISSUE TITLE
Why is this not recommended on macOS?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma-docker#3]
Is there a reason this repository recommends to use a script on macOS?

My concerns, as a user:

- First, it’s generally not the greatest idea to pipe curl’ed script into bash on local machine from security standpoint.

- Second, I see how [that script](https://github.com/riboseinc/metanorma-macos-setup/blob/master/mac) is silently doing many things I would really prefer it not to, such as making a ~/.bin/ directory (my binaries are under ~/bin/).

- I reckon that it would in all likelihood fail on my machine, since I run Homebrew from a different account than the user I generally do daily activities from.

In any case, the currently-live www.metanorma.com recommends using Docker setup and links to this repository, but then this repository recommends using a script instead—which to believe?

If there’s nothing in particular against using the Docker distribution on macOS, I will make a PR or commit to remove the “Recommended” note in this README that links to all-in-one script.

**Comment by ronaldtse** [comment]
@strogonoff ,

1. On macOS, we should recommend using either the Homebrew setup (https://github.com/riboseinc/homebrew-metanorma/) or the Docker setup. We should no longer recommend the "macOS setup script".
2. The Docker setup is mainly for a platform independent way of running Metanorma. From my experience with Metanorma users, they mostly prefer "installing" something rather than running Docker.

**Comment by ronaldtse** [comment]
3. And on Windows, we recommend using the Chocolatey package (https://github.com/riboseinc/chocolatey-metanorma/)

**Comment by strogonoff** [comment]
Awesome, noted

**Comment by strogonoff** [comment]
@ronaldtse can you confirm that instructions [here](https://www.metanorma.com/author/topics/install/) are valid for Windows as far as Chocolatey goes?

The blog post is a bit hazy on the installation command; from a quick search it seemed that `choco install` is the way to go

**Comment by ronaldtse** [comment]
@strogonoff you caught this in an inconvenient time 😉 

The installation command: `choco install metanorma -y` (remember the `-y`) will work -- once the latest Chocolatey Metanorma package (1.1.4) is approved (https://github.com/riboseinc/chocolatey-metanorma/pull/16). However, it has just run into an issue and will take a few more days.

The latest release of the Chocolatey Metanorma package (1.1.3) requires following the steps provided here: https://www.metanorma.com/blog/12-25-2018/metanorma-on-windows-via-chocolatey/

Which is a lot longer:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
cinst ruby --version 2.5.3.101 -y
cinst msys2 --params "/NoUpdate" -y
$env:ChocolateyInstall = Convert-Path "$((Get-Command choco).path)\..\.."
Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
refreshenv
ridk install 2 3
cinst metanorma -y
refreshenv
```

**Comment by ronaldtse** [comment]
(And we don't need the Metanorma Windows install script anymore, https://github.com/riboseinc/metanorma-windows-setup )

**Comment by strogonoff** [comment]
Got it, awesome

**Comment by opoudjis** [comment]
@ronaldtse Does that mean https://github.com/riboseinc/metanorma-windows-setup  should be deprecated? If that is the case, the README needs to say so.

**Comment by strogonoff** [comment]
Yes that’s how I read it, it is no longer referenced on main Metanorma site. Let me do a quick PR to remove this reference, as well as some duplication and potential confusion

**Comment by ronaldtse** [comment]
@strogonoff I'd like to add that Metanorma Docker is still a valid way to install, only "metanorma-windows-setup" isn't.
