### ISSUE TITLE
Is a PlantUML installation included in the container?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma-docker#4]
Title is fairly self-explanatory: will `[plantuml]` blocks be rendered as diagrams when using Docker build? I didn’t find a mention of PlantUML in the Dockerfile.

Would like to avoid building it on my machine right now if possible but @ronaldtse if there’s no certainty off the top of your head then I probably will to ensure this aspect of docs is accurate

**Comment by ronaldtse** [comment]
@strogonoff Yes -- PlantUML is installed on the Docker container via https://github.com/riboseinc/metanorma-linux-setup/blob/master/ubuntu.sh .

**Comment by strogonoff** [comment]
ah I should’ve looked deeper! thanks, will update the diagramming section to clarify
